### PR TITLE
Braille Translator Complete:

### PR DESCRIPTION
**Pull request by jmlc101**
(One commit, One Solution :)
-Created a dictionary of alphabet:braille translation.
-Built alphaToBraille function.
-Built main() function.

### CODE REVIEW

**Comment by jmlc101** [comment]
Line 5 changes string to lowercase.
I don't believe there is uppercase braille?

**Comment by jmlc101** [comment]
Maybe I don't understand.

**Comment by the-vampiire** [comment]
@jmlc101 it is a workaround not a solution. they give you a hint in the problem about what to do with capital letters. take nother look

**Comment by jmlc101** [comment]
I THINK I finally figured out what you were looking for!?!
Thanks for pushing me, great learning experience.

**Pull request merged**
